PG-432 Fixed branch name of a  GH action
percona/pg_stat_monitor pull request #246
Opened 2022-05-30 10:12 UTC by nastena1606

modified:   .github/workflows/doc-build.yml

2022-05-30 10:49 UTC, capri1989 requested changes

2022-05-30 10:49 UTC, capri1989 commented on .github/workflows/doc-build.yml
> +      - REL1_STABLE
The branch name isn't correct. The branch is called "REL_1_STABLE"

2022-06-01 08:52 UTC, nastena1606 commented on .github/workflows/doc-build.yml
> +      - REL1_STABLE
Fixed

2022-06-01 08:54 UTC, capri1989 approved these changes
LGTM

2022-06-01 08:55 UTC, merged