Merging the REL_1_STABLE branch onto the main branch.
percona/pg_stat_monitor pull request #265
Opened 2022-06-17 12:43 UTC by EngineeredVirus

Moving forward, the main branch will be used for development as well as for releases.

2022-06-17 12:43 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/pg_stat_monitor?pullRequest=265) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/pg_stat_monitor?pullRequest=265) before we can accept your contribution.<br/>**3** out of **8** committers have signed the CLA.<br/><br/>:white_check_mark: puneet0191<br/>:white_check_mark: ibrarahmad<br/>:white_check_mark: EngineeredVirus<br/>:x: EvgeniyPatlan<br/>:x: nastena1606<br/>:x: capri1989<br/>:x: Naeem-Akhter<br/>:x: Ibrar Ahmed<br/><hr/>**Ibrar Ahmed** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/pg_stat_monitor?pullRequest=265) it.</sub>

2022-06-17 19:56 UTC, ibrarahmad requested changes

2022-06-17 19:56 UTC, ibrarahmad commented on META.json
> +   "version": "1.0.1",
I think in main we need to keep version dev

2022-06-17 19:56 UTC, ibrarahmad commented on META.json
> +         "version": "1.0.1"
Same here we need to keep dev version in main branch

2022-06-17 19:56 UTC, ibrarahmad commented on README.md
> +![PostgreSQL-11](https://github.com/percona/pg_stat_monitor/workflows/postgresql-11-build/badge.svg?branch=REL_1_STABLE) ![PostgreSQL-11-Package](https://github.com/percona/pg_stat_monitor/workflows/
These all changes are not reuired

2022-06-17 19:56 UTC, ibrarahmad commented on pg_stat_monitor.c
Version issue

2022-06-17 19:56 UTC, ibrarahmad commented on t/expected/017_execution_stats.out
> + SELECT pg_stat_monitor_reset()                                                                                            |     1 |          0.0302 |        0.0302 |        0.0302 |         0.0302 |
Are we 100% sure about these number changes?

2022-06-18 10:35 UTC, EngineeredVirus commented on META.json
> +         "version": "1.0.1"
I think the main branch should carry the latest released version.

2022-06-18 10:35 UTC, EngineeredVirus commented on META.json
> +   "version": "1.0.1",
I think the main branch should carry the latest released version.

2022-06-18 10:43 UTC, EngineeredVirus commented on README.md
> +![PostgreSQL-11](https://github.com/percona/pg_stat_monitor/workflows/postgresql-11-build/badge.svg?branch=REL_1_STABLE) ![PostgreSQL-11-Package](https://github.com/percona/pg_stat_monitor/workflows/
Resolved.

2022-06-18 10:44 UTC, puneet0191 commented
@Naeem-Akhter could you please help, when this PR is merged we would need to update all testing default branches too

2022-06-18 10:44 UTC, EngineeredVirus commented on t/expected/017_execution_stats.out
> + SELECT pg_stat_monitor_reset()                                                                                            |     1 |          0.0302 |        0.0302 |        0.0302 |         0.0302 |
The regression is working fine. Is there another way to reconfirm these?

2022-06-18 10:45 UTC, EngineeredVirus commented on pg_stat_monitor.c
I think the main branch should carry the latest released version.

2022-06-19 08:49 UTC, EngineeredVirus commented on t/expected/017_execution_stats.out
> + SELECT pg_stat_monitor_reset()                                                                                            |     1 |          0.0302 |        0.0302 |        0.0302 |         0.0302 |
I've re-reviewed the output. If there needs some fixing for the test cases let's move do that after the merge. @Naeem-Akhter

2022-06-19 08:56 UTC, EngineeredVirus commented on META.json
> +   "version": "1.0.1",
I've updated the version to 1.1.0-dev

2022-06-19 20:06 UTC, ibrarahmad commented
@EngineeredVirus You need to Squash the commit.

2022-06-20 09:39 UTC, capri1989 requested changes
LGTM apart from the open question on the docs workflow

2022-06-20 09:39 UTC, capri1989 commented on META.json
> +   "version": "1.1.0-dev",
I'm fine with that change as this always indicates the next upcoming version already and this can easily be updated during the branch of for the next release.

2022-06-20 12:20 UTC, ibrarahmad approved these changes

2022-06-20 12:21 UTC, ibrarahmad approved these changes

2022-06-20 12:21 UTC, capri1989 commented on META.json
> +   "version": "1.1.0-dev",
As discussed and agreed, we keep it in and it will be moved out anyway as part of documentation move to another repository.

2022-06-20 12:22 UTC, ibrarahmad approved these changes

2022-06-20 12:22 UTC, capri1989 approved these changes
LGTM

2022-06-20 12:22 UTC, merged