PG-476: pg_stat_monitor causing errors : could not read file /tmp/pg_…
percona/pg_stat_monitor pull request #289
Opened 2022-08-04 09:11 UTC by EngineeredVirus

…stat_monitor_query: No such file or directory

This only fixes the basic the path issue. It moves the query overflow file
from /tmp to PGSTAT folder data directory.

2022-08-08 10:38 UTC, ibrarahmad requested changes

2022-08-08 10:38 UTC, ibrarahmad commented on pg_stat_monitor.c
> +#define PGSM_TEXT_FILE PGSTAT_STAT_PERMANENT_DIRECTORY "pg_stat_monitor_query"
1 - Please check that if pg_stat_statment is never installed on that system, will that work?
2 - It will create confusion to share the pg_stat_stetment directory with pg_stat_monitor.

2022-08-09 11:11 UTC, EngineeredVirus commented on pg_stat_monitor.c
> +#define PGSM_TEXT_FILE PGSTAT_STAT_PERMANENT_DIRECTORY "pg_stat_monitor_query"
This define is part of pg_stat, not pg_stat_statements. So we are good with it. I've verified that this should work for all supported versions of PG11 onwards.

2022-08-09 16:22 UTC, ibrarahmad approved these changes

2022-08-09 16:22 UTC, merged