PG-475: Inconsistent behaviour of PGSM
percona/pg_stat_monitor pull request #295
Opened 2022-08-22 08:41 UTC by EngineeredVirus

Reverting the bucket locking mechanism to previous behavior. This has
a lot of room for improvement that needs to be part of a major refactoring
in the 2.x release.

2022-08-22 14:34 UTC, ibrarahmad requested changes
The patch should contain the changes required; no code cleanup and whitespace changes are not allowed in the bug fix commit.

2022-08-22 14:34 UTC, ibrarahmad commented on pg_stat_monitor.c
> +    struct timeval  tv;
Why do we have whitespace changes? Even if the previous is wrong, that should not be here in a fix.

2022-08-22 15:37 UTC, EngineeredVirus commented on pg_stat_monitor.c
> +    struct timeval  tv;
Updated the whitespaces to match the current whitespace settings. Previous patch had the same whitespace as the original code.

2022-08-23 18:23 UTC, ibrarahmad approved these changes
LGTM

2022-08-23 18:24 UTC, merged