PG-564: Added a column to display bind variables when used with the n…
percona/pg_stat_monitor pull request #350
Opened 2023-01-09 09:54 UTC by kayform

…ormalized_query option.

When collecting data for monitoring, display it as placeholders using the pgsm_normalized_query option.
If bind parameter and "normalized query are retrieved together as attached the image, it would be more useful for query performance analysis.

2023-01-25 10:43 UTC, ibrarahmad requested changes
Please add some test cases for that.

2023-01-25 10:44 UTC, ibrarahmad requested changes
pg_stat_monitor-1.0-2.0.sql need to be updated

2023-03-14 08:26 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/pg_stat_monitor?pullRequest=350) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/pg_stat_monitor?pullRequest=350) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: kayform<br/>:x: snsjeong<br/><hr/>**snsjeong** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/pg_stat_monitor?pullRequest=350) it.</sub>

2026-02-10 08:37 UTC, AndersAstrand commented
I'm not entirely sure I understand the purpose of this. Just as when `pgsm_normalized_query` is turned off, the values you will get is just for the first execution of the normalized query anyways. This column doesn't add any extra information above what `pgsm_normalized_query = off` will already give you, right?

Or am I completely misunderstanding what you want to accomplish here?

2026-02-10 09:22 UTC, AndersAstrand commented
Seems related to #481 and #517

2026-03-03 12:19 UTC, AndersAstrand commented
I'll close this as we seem to have lost the original creator when we just left it on read for 2 years.

2026-03-03 12:19 UTC, closed without merging