PG-147 Stored Procedure Support add parentid to track caller
percona/pg_stat_monitor pull request #72
Opened 2021-02-04 04:00 UTC by MartinSun34

This patch will add a colum in pg_stat_monitor, it will record the outer layer caller's pueryid as inner layer query's parentid.

Review by @EngineeredVirus

2021-02-08 09:42 UTC, EngineeredVirus requested changes
We also must update the pgssHashKey structure to include the parentid. Also, please do update the relevant code.

2021-02-08 09:42 UTC, EngineeredVirus commented on pg_stat_monitor.h
> +#define DEFAULT_MAX_NESTED_LEVEL	10
Why a value of 10 and why not less or more? Realistically, I'd suggest to use max_stack_depth value.

2021-02-08 09:42 UTC, EngineeredVirus commented on sql/basic.sql
> +SELECT query FROM pg_stat_monitor ORDER BY query COLLATE "C";
This should be part of another separate patch for regression. Also, I think that we should change the query so that its output is not collation dependent.

2021-02-08 09:42 UTC, EngineeredVirus commented on pg_stat_monitor.c
> +			e->counters.info.parentid = UINT64CONST(0);
I'd suggest to #define an empty parentid rather than using this const value; perhaps:

#define QUERY_PARENT_NONE UINT64CONST(0)

2021-02-10 16:47 UTC, ibrarahmad commented
The patch does now work for me, please check that.

```
postgres=# select * from add(1,2);
 add 
-----
   3
(1 row)

postgres=# select prosrc from pg_proc where proname like 'add';
     prosrc      
-----------------
 select $1 + $2;
(1 row)


postgres=# select queryid, substr(query, 0, 30), parentid from pg_stat_monitor;
     queryid      |            substr             | parentid 
------------------+-------------------------------+----------
 D64C8DB8CD001F18 | select prosrc from pg_proc wh | 
 E12B4104FD85859A | select $1 + $2                | 
 96C96A98020966B5 | select * from add($1,$2)      | 
 3BBF759969838E17 | SELECT pg_catalog.quote_ident | 
 CC9AF910C6E0189D | select queryid, substr(query, | 
(5 rows)
```

2021-02-16 17:07 UTC, ibrarahmad commented
After fixing the issue mentioned by Hamid and identified by me. I have committed the patch.

2021-02-16 17:07 UTC, closed without merging